spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bespokebids
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: create
      #ddl-auto: validate
    properties:
      hibernate:
        #show_sql: true
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
